require("config.options")
require("config.autocmds")
require("config.keymaps")
require("config.packages")
require("plugins.ui.rose-pine")
require("plugins.navigation.snacks")
require("plugins.navigation.yazi")
